def roll(con):
    mod=[]
    if con==1:
        mod.append("0")
        mod.append("-8")
        mod.append("-7")
        mod.append("-")
        mod.append("-")
    elif con==2:
        mod.append("1")
        mod.append("-7")
        mod.append("-6")
        mod.append("-")
        mod.append("-")
    elif con==3:
        mod.append("1")
        mod.append("-6")
        mod.append("-5")
        mod.append("-")
        mod.append("-")
    elif con==4:
        mod.append("1")
        mod.append("-5")
        mod.append("-4")
        mod.append("-")
        mod.append("-")
    elif con==5:
        mod.append("2")
        mod.append("-4")
        mod.append("-3")
        mod.append("-")
        mod.append("-")
    elif con==6:
        mod.append("2")
        mod.append("-3")
        mod.append("-2")
        mod.append("-")
        mod.append("-")
    elif con==7:
        mod.append("3")
        mod.append("-2")
        mod.append("-1")
        mod.append("-")
        mod.append("-")
    elif con==8:
        mod.append("3")
        mod.append("-1")
        mod.append("0")
        mod.append("-")
        mod.append("-")
    elif con>9 and con<12:
        mod.append("4")
        mod.append("0")
        mod.append("0")
        mod.append("-")
        mod.append("-")
    elif con==12:
        mod.append("5")
        mod.append("0")
        mod.append("0")
        mod.append("-")
        mod.append("-")
    elif con==13:
        mod.append("5")
        mod.append("0")
        mod.append("+1")
        mod.append("-")
        mod.append("-")
    elif con==14:
        mod.append("6")
        mod.append("+1")
        mod.append("+2")
        mod.append("-")
        mod.append("-")
    elif con==15:
        mod.append("7")
        mod.append("+3")
        mod.append("+3")
        mod.append("-")
        mod.append("-")
    elif con==16:
        mod.append("8")
        mod.append("+4")
        mod.append("+5")
        mod.append("-")
        mod.append("-")
    elif con==17:
        mod.append("10")
        mod.append("+6")
        mod.append("+6")
        mod.append("-")
        mod.append("-")
    elif con==18:
        mod.append("15")
        mod.append("+8")
        mod.append("+7")
        mod.append("-")
        mod.append("-")
    elif con==19:
        mod.append("20")
        mod.append("+10")
        mod.append("+8")
        mod.append("!")
        mod.append("1st")
    elif con==20:
        mod.append("25")
        mod.append("+12")
        mod.append("+9")
        mod.append("!!")
        mod.append("2nd")
    elif con==21:
        mod.append("30")
        mod.append("+14")
        mod.append("+10")
        mod.append("!!!")
        mod.append("3rd")
    elif con==22:
        mod.append("35")
        mod.append("+16")
        mod.append("+11")
        mod.append("!!!!")
        mod.append("4th")
    elif con==23:
        mod.append("40")
        mod.append("+18")
        mod.append("+12")
        mod.append("!!!!!")
        mod.append("5th")
    elif con==24:
        mod.append("45")
        mod.append("+20")
        mod.append("+13")
        mod.append("!!!!!!")
        mod.append("6th")
    elif con==25:
        mod.append("50")
        mod.append("+20")
        mod.append("+14")
        mod.append("!!!!!!!")
        mod.append("7th")
    return mod
