def roll(str):
    mod=[]
    if str==1:
        mod.append("-5")
        mod.append("-4")
        mod.append("1")
        mod.append("3")
        mod.append("1")
        mod.append("0%")
    elif str==2:
        mod.append("-3")
        mod.append("-2")
        mod.append("1")
        mod.append("5")
        mod.append("1")
        mod.append("0%")
    elif str==3:
        mod.append("-3")
        mod.append("-1")
        mod.append("5")
        mod.append("10")
        mod.append("2")
        mod.append("0%")
    elif str>3 and str<6:
        mod.append("-2")
        mod.append("-1")
        mod.append("10")
        mod.append("25")
        mod.append("3")
        mod.append("0%")
    elif str>5 and str<8:
        mod.append("-1")
        mod.append("0")
        mod.append("20")
        mod.append("55")
        mod.append("4")
        mod.append("0%")
    elif str>7 and str<10:
        mod.append("0")
        mod.append("0")
        mod.append("35")
        mod.append("90")
        mod.append("5")
        mod.append("1%")
    elif str>9 and str<12:
        mod.append("0")
        mod.append("0")
        mod.append("40")
        mod.append("115")
        mod.append("6")
        mod.append("2%")
    elif str>11 and str<14:
        mod.append("0")
        mod.append("0")
        mod.append("45")
        mod.append("140")
        mod.append("7")
        mod.append("4%")
    elif str>13 and str<16:
        mod.append("0")
        mod.append("0")
        mod.append("55")
        mod.append("170")
        mod.append("8")
        mod.append("7%")
    elif str==16:
        mod.append("0")
        mod.append("1")
        mod.append("70")
        mod.append("195")
        mod.append("9")
        mod.append("10%")
    elif str==17:
        mod.append("1")
        mod.append("1")
        mod.append("85")
        mod.append("220")
        mod.append("10")
        mod.append("13%")
    elif str==18:
        mod.append("1")
        mod.append("2")
        mod.append("110")
        mod.append("255")
        mod.append("11")
        mod.append("16%")
    elif str>18 and str<18.51:
        mod.append("1")
        mod.append("3")
        mod.append("135")
        mod.append("280")
        mod.append("12")
        mod.append("20%")
    elif str>18.5 and str<18.76:
        mod.append("2")
        mod.append("3")
        mod.append("160")
        mod.append("305")
        mod.append("13")
        mod.append("25%")
    elif str>18.75 and str<18.91:
        mod.append("2")
        mod.append("4")
        mod.append("185")
        mod.append("330")
        mod.append("14")
        mod.append("30%")
    elif str>18.90 and str<19:
        mod.append("2")
        mod.append("5")
        mod.append("235")
        mod.append("380")
        mod.append("15-3")
        mod.append("35%")
    elif str==19:
        mod.append("3")
        mod.append("7")
        mod.append("485")
        mod.append("640")
        mod.append("16-8")
        mod.append("50%")
    elif str==20:
        mod.append("3")
        mod.append("8")
        mod.append("535")
        mod.append("700")
        mod.append("17-10")
        mod.append("60%")
    elif str==21:
        mod.append("4")
        mod.append("9")
        mod.append("635")
        mod.append("810")
        mod.append("17-12")
        mod.append("70%")
    elif str==22:
        mod.append("4")
        mod.append("10")
        mod.append("785")
        mod.append("970")
        mod.append("18-14")
        mod.append("80%")
    elif str==23:
        mod.append("5")
        mod.append("11")
        mod.append("935")
        mod.append("1130")
        mod.append("18-16")
        mod.append("90%")
    elif str==24:
        mod.append("6")
        mod.append("12")
        mod.append("1235")
        mod.append("1440")
        mod.append("19-17")
        mod.append("95%")
    elif str==25:
        mod.append("7")
        mod.append("14")
        mod.append("1535")
        mod.append("1750")
        mod.append("19-18")
        mod.append("99%")

    return mod
