def roll(dosh,wplist)
    weapons=[]
    weapons.append(dosh)    #sets dosh as the 0 value

    while len(wplist)>0:
        if wplist[0]=="Battleaxe" and dosh>500:
            RoF="M"
            atkadj="Str"
            dmgadj="Str"
            Damage="1D8/1D8"
            Range="Melee"
            Type="S"
            Speed="7"
            Weight="7"
            dosh=dosh-500
            wplist.pop([0])
        elif wplist[0]=="Blowgun" and dosh>500:
            RoF="2"
            atkadj="Dex"
            dmgadj=0
            Damage="Ammunition"
            Range="10/20/30"
            Type="N/A"
            Speed="5"
            Weight="2"
            dosh=dosh-500
            wplist.pop([0])
        elif wplist[0]=="Composite Longbow" and dosh>10000:
            RoF="2"
            atkadj="Dex"
            dmgadj="Str"
            Damage="Ammunition"
            Range="Ammunition"
            Type="N/A"
            Speed="6"
            Weight="3"
            dosh=dosh-10000
            wplist.pop([0])
        elif wplist[0]=="Composite Shortbow" and dosh>7500:
            RoF="2"
            atkadj="Dex"
            dmgadj="Str"
            Damage="Ammunition"
            Range="50/100/180"
            Type="N/A"
            Speed="7"
            Weight="2"
            dosh=dosh-7500
            wplist.pop([0])
        elif wplist[0]=="Longbow" and dosh>7500:
            RoF="2"
            atkadj="Dex"
            dmgadj="0"
            Damage="Ammunition"
            Range="Ammunition"
            Type="N/A"
            Speed="8"
            Weight="3"
            dosh=dosh-7500
            wplist.pop([0])
        elif wplist[0]=="Shortbow" and dosh>3000:
            RoF="2"
            atkadj="Dex"
            dmgadj="0"
            Damage="Ammunition"
            Range="Ammunition"
            Type="N/A"
            Speed="7"
            Weight="2"
            dosh=dosh-3000
            wplist.pop([0])
        elif wplist[0]=="Bola" and dosh>50:
            RoF="Thrown"
            atkadj="Dex"
            dmgadj="0"
            Damage="1D3/1D2"
            Range="10/20/30"
            Type="N/A"
            Speed="8"
            Weight="2"
            dosh=dosh-50
            wplist.pop([0])
        elif wplist[0]=="Chain" and dosh>50:
            RoF="M"
            atkadj="Str"
            dmgadj="Str"
            Damage="1D4+1/1D4"
            Range="Melee"
            Type="B"
            Speed="5"
            Weight="3"
            dosh=dosh-50
            wplist.pop([0])
        elif wplist[0]=="Club" and dosh>0:
            RoF="M"
            atkadj="Str"
            dmgadj="Str"
            Damage="1D6/1D3"
            Range="Melee"
            Type="B"
            Speed="4"
            Weight="3"
            dosh=dosh-0
            wplist.pop([0])
        elif wplist[0]=="Hand Crossbow" and dosh>30000:
            RoF="1"
            atkadj="Dex"
            dmgadj=""
            Damage="1D3/1D2"
            Range="20/40/60"
            Type="P"
            Speed="5"
            Weight="3"
            dosh=dosh-30000
            wplist.pop([0])
        elif wplist[0]=="Crossbow" and dosh>3500:
            RoF="1"
            atkadj="Dex"
            dmgadj="+1"
            Damage="1D4/1D4"
            Range="60/120/180"
            Type="P"
            Speed="7"
            Weight="7"
            dosh=dosh-3500
            wplist.pop([0])
        elif wplist[0]=="Heavy Crossbow" and dosh>5000:
            RoF="1/2"
            atkadj="Dex"
            dmgadj="+6"
            Damage="1D4+1/1D6+1"
            Range="80/160/240"
            Type="P"
            Speed="10"
            Weight="14"
            dosh=dosh-5000
            wplist.pop([0])
        elif wplist[0]=="Dagger" and dosh>200:
            RoF="M"
            atkadj="Str"
            dmgadj="Str"
            Damage="1D4/1D3"
            Range="60/120/180"
            Type="P"
            Speed="2"
            Weight="1"
            dosh=dosh-200
            wplist.pop([0])
        elif wplist[0]=="Dagger" and dosh>200:
            RoF="M"
            atkadj="Str"
            dmgadj="Str"
            Damage="1D4/1D3"
            Range="10/20/30"
            Type="P"
            Speed="2"
            Weight="1"
            dosh=dosh-200
            wplist.pop([0])
        elif wplist[0]=="Parrying Dagger" and dosh>500:
            RoF="M"
            atkadj="Str"
            dmgadj="Str"
            Damage="1D3/1D3"
            Range="Melee"
            Type="P"
            Speed="2"
            Weight="1"
            dosh=dosh-500
            wplist.pop([0])
        elif wplist[0]=="Dart" and dosh>50:
            RoF="3"
            atkadj="Dex"
            dmgadj="0"
            Damage="1D3/1D2"
            Range="10/20/30"
            Type="P"
            Speed="2"
            Weight=".5"
            dosh=dosh-50
            wplist.pop([0])
        elif wplist[0]=="Footman's Flail" and dosh>1500:
            RoF="M"
            atkadj="Str"
            dmgadj="Str"
            Damage="1D6+1/1D4+1"
            Range="Melee"
            Type="B"
            Speed="7"
            Weight="15"
            dosh=dosh-1500
            wplist.pop([0])
        elif wplist[0]=="Horseman's Flail" and dosh>800:
            RoF="M"
            atkadj="Str"
            dmgadj="Str"
            Damage="1D4+1/1D4+1"
            Range="Melee"
            Type="B"
            Speed="6"
            Weight="5"
            dosh=dosh-800
            wplist.pop([0])
        elif wplist[0]=="Gaff/Hook" and dosh>200:
            RoF="M"
            atkadj="Str"
            dmgadj="Str"
            Damage="1D4/1D3"
            Range="Melee"
            Type="S"
            Speed="2"
            Weight="2"
            dosh=dosh-200
            wplist.pop([0])
        elif wplist[0]=="Hand Axe" and dosh>100:
            RoF="M"
            atkadj="Str"
            dmgadj="Str"
            Damage="1D6/1D4"
            Range="10/20/30"
            Type="S"
            Speed="4"
            Weight="5"
            dosh=dosh-100
            wplist.pop([0])
        elif wplist[0]=="Harpoon" and dosh>2000:
            RoF="M"
            atkadj="Str"
            dmgadj="Str"
            Damage="2H"
            Range="Melee"
            Type="P"
            Speed="7"
            Weight="6"
            dosh=dosh-2000
            wplist.pop([0])
        elif wplist[0]=="Javelin" and dosh>50:
            RoF="M"
            atkadj="Str/Dex"
            dmgadj="Str"
            Damage="2H"
            Range="20/60/80"
            Type="P"
            Speed="4"
            Weight="2"
            dosh=dosh-50
            wplist.pop([0])
        elif wplist[0]=="Knife" and dosh>50:
            RoF="M"
            atkadj="Str"
            dmgadj="Str"
            Damage="1D3/1D2"
            Range="Melee"
            Type="P/S"
            Speed="2"
            Weight=".5"
            dosh=dosh-50
            wplist.pop([0])
        elif wplist[0]=="Heavy Horse Lance" and dosh>1500:
            RoF="M"
            atkadj="Str"
            dmgadj="Str"
            Damage="1D8+1/1D6"
            Range="Melee"
            Type="P"
            Speed="8"
            Weight="15"
            dosh=dosh-1500
            wplist.pop([0])
        elif wplist[0]=="Jousting Lance" and dosh>2000:
            RoF="M"
            atkadj="Str"
            dmgadj="Str"
            Damage="1D3-1/1D2-1"
            Range="Melee"
            Type="P"
            Speed="10"
            Weight="20"
            dosh=dosh-2000
            wplist.pop([0])
        elif wplist[0]=="Light Horse Lance" and dosh>500:
            RoF="M"
            atkadj="Str"
            dmgadj="Str"
            Damage="1D6/1D8"
            Range="Melee"
            Type="P"
            Speed="6"
            Weight="5"
            dosh=dosh-500
            wplist.pop([0])
        elif wplist[0]=="Medium Horse Lance" and dosh>1000:
            RoF="M"
            atkadj="Str"
            dmgadj="Str"
            Damage="1D6+1/2D6"
            Range="Melee"
            Type="P"
            Speed="7"
            Weight="10"
            dosh=dosh-1000
            wplist.pop([0])
        elif wplist[0]=="Lasso" and dosh>50:
            RoF="M"
            atkadj="Dex"
            dmgadj="0"
            Damage="-/-"
            Range="10/20/30"
            Type="-"
            Speed="10"
            Weight="3"
            dosh=dosh-50
            wplist.pop([0])
        elif wplist[0]=="Main-Gauche" and dosh>300:
            RoF="M"
            atkadj="Str"
            dmgadj="Str"
            Damage="1D4/1D3"
            Range="Melee"
            Type="P"
            Speed="2"
            Weight="2"
            dosh=dosh-300
            wplist.pop([0])
        elif wplist[0]=="Mancatcher" and dosh>3000:
            RoF="M"
            atkadj="Str"
            dmgadj="Str"
            Damage="-/-"
            Range="Melee"
            Type="S/P"
            Speed="7"
            Weight="8"
            dosh=dosh-3000
            wplist.pop([0])
        elif wplist[0]=="Morning Star" and dosh>1000:
            RoF="M"
            atkadj="Str"
            dmgadj="Str"
            Damage="2D4/1D6+1"
            Range="Melee"
            Type="P"
            Speed="7"
            Weight="12"
            dosh=dosh-1000
            wplist.pop([0])
        elif wplist[0]=="Net" and dosh>500:
            RoF="M"
            atkadj="Dex"
            dmgadj="-"
            Damage="-/-"
            Range="10/20/30"
            Type="-"
            Speed="10"
            Weight="10"
            dosh=dosh-500
            wplist.pop([0])
        elif wplist[0]=="Awl Pike" and dosh>500: #double damage when reciving a charge
            RoF="M"
            atkadj="Str"
            dmgadj="Str"
            Damage="1D6/1D12"
            Range="Melee"
            Type="P"
            Speed="13"
            Weight="12"
            dosh=dosh-500
            wplist.pop([0])
        elif wplist[0]=="Bariche" and dosh>700: #Used as a mount for guns
            RoF="M"
            atkadj="Str"
            dmgadj="Str"
            Damage="2D4/2D6"
            Range="Melee"
            Type="S"
            Speed="9"
            Weight="12"
            dosh=dosh-700
            wplist.pop([0])
        elif wplist[0]=="Bec De Corbin" and dosh>800: #Removes armour on a called shot
            RoF="M"
            atkadj="Str"
            dmgadj="Str"
            Damage="1D8/1D6"
            Range="Melee"
            Type="P"
            Speed="9"
            Weight="10"
            dosh=dosh-800
            wplist.pop([0])
        elif wplist[0]=="Bill" and dosh>700: #Improvised from a machette, supplies can be found near forrestry industries. Dismounts riders on successful hit.
            RoF="M"
            atkadj="Str"
            dmgadj="Str"
            Damage="2D4/1D10"
            Range="Melee"
            Type="P/S"
            Speed="10"
            Weight="15"
            dosh=dosh-700
            wplist.pop([0])
        elif wplist[0]=="Fauchard" and dosh>500: #Improvised from a sickle designed to cut down fruit. Can be used to hook objects and enemies.
            RoF="M"
            atkadj="Str"
            dmgadj="Str"
            Damage="1D8/1D10"
            Range="Melee"
            Type="P/S"
            Speed="8"
            Weight="7"
            dosh=dosh-500
            wplist.pop([0])
        elif wplist[0]=="Glaive" and dosh>600: #Double damage when charging large creatures
            RoF="M"
            atkadj="Str"
            dmgadj="Str"
            Damage="2D4/2D6"
            Range="Melee"
            Type="S"
            Speed="8"
            Weight="8"
            dosh=dosh-600
            wplist.pop([0])
        elif wplist[0]=="Guisarme" and dosh>500:
            RoF="M"
            atkadj="Str"
            dmgadj="Str"
            Damage="2D4/2D6"
            Range="Melee"
            Type="P"
            Speed="7"
            Weight="8"
            dosh=dosh-500
            wplist.pop([0])
        elif wplist[0]=="Halberd" and dosh>1000:
            RoF="M"
            atkadj="Str"
            dmgadj="Str"
            Damage="1D10/2D6"
            Range="Melee"
            Type="S/P"
            Speed="9"
            Weight="15"
            dosh=dosh-1000
            wplist.pop([0])
        elif wplist[0]=="Military Fork" and dosh>500: #Double damage while charging against large creatures. A modified pitchfork can be used as a piton to climb walls and lifting objects.
            RoF="M"
            atkadj="Str"
            dmgadj="Str"
            Damage="1D8/2D4"
            Range="Melee"
            Type="P"
            Speed="9"
            Weight="8"
            dosh=dosh-500
            wplist.pop([0])
        elif wplist[0]=="Partisian" and dosh>1000: #Double damage when recieving a charge. Can break weapon on a successful parry. Has a broad head great for engraving
            RoF="M"
            atkadj="Str"
            dmgadj="Str"
            Damage="1D6/1D6+1"
            Range="Melee"
            Type="P"
            Speed="9"
            Weight="8"
            dosh=dosh-1000
            wplist.pop([0])
        elif wplist[0]=="Ranseur" and dosh>600: #Double damage when recieving a charge. On called shot -4 can either disarm or ignore armour
            RoF="M"
            atkadj="Str"
            dmgadj="Str"
            Damage="2D4/2D4"
            Range="Melee"
            Type="P"
            Speed="7"
            Weight="8"
            dosh=dosh-600
            wplist.pop([0])
        elif wplist[0]=="Spetum" and dosh>500: #Double damage when reciving a charge. Blades on the reverse side cause 1d2 after hitting on a roll of 18+ or called shot -2
            RoF="M"
            atkadj="Str"
            dmgadj="Str"
            Damage="1D6/1D6+1"
            Range="Melee"
            Type="P"
            Speed="7"
            Weight="8"
            dosh=dosh-500
            wplist.pop([0])
        elif wplist[0]=="Volgue" and dosh>500: #Double damage on reciving a charge. Skilled users can improvise one from any pole and blade.
            RoF="M"
            atkadj="Str"
            dmgadj="Str"
            Damage="2D4/2D4"
            Range="Melee"
            Type="S"
            Speed="10"
            Weight="15"
            dosh=dosh-500
            wplist.pop([0])
        elif wplist[0]=="Quarterstaff" and dosh>0:
            RoF="M"
            atkadj="Str"
            dmgadj="Str"
            Damage="1D6/1D6"
            Range="Melee"
            Type="B"
            Speed="4"
            Weight="4"
            dosh=dosh-0
            wplist.pop([0])
        elif wplist[0]=="Sap" and dosh>100: #75% of damage is non-lethal. -8 called shot for knock-out, 5% chance for every damage done, 10% for Coup-de-Grace. 
            RoF="M"
            atkadj="Str"
            dmgadj="Str"
            Damage="1D2/1D2"
            Range="Melee"
            Type="B"
            Speed="5"
            Weight=".1"
            dosh=dosh-100
            wplist.pop([0])
        elif wplist[0]=="Scourge" and dosh>100: #forces morale check on creatures on damage
            RoF="M"
            atkadj="Str"
            dmgadj="Str"
            Damage="1D4/1D2"
            Range="Melee"
            Type="S"
            Speed="5"
            Weight="2"
            dosh=dosh-100
            wplist.pop([0])
        elif wplist[0]=="Sickle" and dosh>60:
            RoF="M"
            atkadj="Str"
            dmgadj="Str"
            Damage="1D4+1/1D4"
            Range="Melee"
            Type="S"
            Speed="4"
            Weight="3"
            dosh=dosh-60
            wplist.pop([0])
        elif wplist[0]=="Sling" and dosh>5:
            RoF="M"
            atkadj="Dex"
            dmgadj="0"
            Damage="Ammunition"
            Range="Ammunition"
            Type="B"
            Speed="6"
            Weight=".1"
            dosh=dosh-5
            wplist.pop([0])
        elif wplist[0]=="Spear" and dosh>80: #If wielded two handed can be set to recieve a charge for double damage.
            RoF="M"
            atkadj="Str"
            dmgadj="Str"
            Damage="2H"
            Range="Melee"
            Type="P"
            Speed="6"
            Weight="5"
            dosh=dosh-80
            wplist.pop([0])
        elif wplist[0]=="Long Spear" and dosh>500: #If wielded two handed can be set to recieve a charge for double damage.
            RoF="M"
            atkadj="Str"
            dmgadj="Str"
            Damage="2H"
            Range="Melee"
            Type="P"
            Speed="8"
            Weight="8"
            dosh=dosh-500
            wplist.pop([0])
        elif wplist[0]=="Staff Sling" and dosh>20: #Designed to lob objects like grenades, oils and large rocks
            RoF="M"
            atkadj="Dex"
            dmgadj="0"
            Damage="Ammunition"
            Range="0/30-60/90"
            Type="B"
            Speed="11"
            Weight="2"
            dosh=dosh-20
            wplist.pop([0])
        elif wplist[0]=="Stiletto" and dosh>50: #Easily concealed. +2 to attack against metal armoured enemies.
            RoF="M"
            atkadj="Str"
            dmgadj="Str"
            Damage="1d3/1d2"
            Range="Melee"
            Type="P"
            Speed="2"
            Weight=".5"
            dosh=dosh-50
            wplist.pop([0])
        elif wplist[0]=="Bastard Sword" and dosh>2500:
            RoF="M"
            atkadj="Str"
            dmgadj="Str"
            Damage="2H"
            Range="Melee"
            Type="S"
            Speed="6"
            Weight="10"
            dosh=dosh-2500
            wplist.pop([0])
        elif wplist[0]=="Broadsword" and dosh>1000:
            RoF="M"
            atkadj="Str"
            dmgadj="Str"
            Damage="2d4/1d6+1"
            Range="Melee"
            Type="S"
            Speed="5"
            Weight="4"
            dosh=dosh-1000
            wplist.pop([0])
        elif wplist[0]=="Cutlass" and dosh>1200:
            RoF="M"
            atkadj="Str"
            dmgadj="Str"
            Damage="1d6/1d8"
            Range="Melee"
            Type="S"
            Speed="5"
            Weight="4"
            dosh=dosh-1200
            wplist.pop([0])
        elif wplist[0]=="Falchion" and dosh>1700:
            RoF="M"
            atkadj="Str"
            dmgadj="Str"
            Damage="1d6+1/2D4"
            Range="Melee"
            Type="S"
            Speed="5"
            Weight="8"
            dosh=dosh-1700
            wplist.pop([0])
        elif wplist[0]=="Long Sword" and dosh>1500:
            RoF="M"
            atkadj="Str"
            dmgadj="Str"
            Damage="1d8/1d12"
            Range="Melee"
            Type="S"
            Speed="5"
            Weight="8"
            dosh=dosh-1500
            wplist.pop([0])
        elif wplist[0]=="Rapier" and dosh>1500:
            RoF="M"
            atkadj="Str"
            dmgadj="Str"
            Damage="1D6+1/1D8+1"
            Range="Melee"
            Type="P"
            Speed="4"
            Weight="4"
            dosh=dosh-1500
            wplist.pop([0])
        elif wplist[0]=="Sabre" and dosh>1700:
            RoF="M"
            atkadj="Str"
            dmgadj="Str"
            Damage="1d6+1/1d8+1"
            Range="Melee"
            Type="S"
            Speed="4"
            Weight="5"
            dosh=dosh-1700
            wplist.pop([0])
        elif wplist[0]=="Scimitar" and dosh>1500: #Can be used to break inanimate objects
            RoF="M"
            atkadj="Str"
            dmgadj="Str"
            Damage="1d8/1d8"
            Range="Melee"
            Type="S"
            Speed="5"
            Weight="4"
            dosh=dosh-1500
            wplist.pop([0])
        elif wplist[0]=="Short Sword" and dosh>1000:
            RoF="M"
            atkadj="Str"
            dmgadj="Str"
            Damage="1d6/1d8"
            Range="Melee"
            Type="S"
            Speed="2"
            Weight=".5"
            dosh=dosh-1000
            wplist.pop([0])
        elif wplist[0]=="Zweihander" and dosh>5000:
            RoF="M"
            atkadj="Str"
            dmgadj="Str"
            Damage="1D10/3d6"
            Range="Melee"
            Type="S"
            Speed="10"
            Weight="15"
            dosh=dosh-5000
            wplist.pop([0])
        elif wplist[0]=="Trident" and dosh>1500:
            RoF="M"
            atkadj="Str"
            dmgadj="Str"
            Damage="2H"
            Range="Melee"
            Type="P"
            Speed="7"
            Weight="5"
            dosh=dosh-1500
            wplist.pop([0])
        elif wplist[0]=="Warhammer" and dosh>200:
            RoF="M"
            atkadj="Str"
            dmgadj="Str"
            Damage="1d4+1/1d4"
            Range="Melee"
            Type="B"
            Speed="4"
            Weight="6"
            dosh=dosh-200
            wplist.pop([0])
        elif wplist[0]=="Whip" and dosh>10: #Called shot -4 to disarm, on any hit a limb may be entangled.
            RoF="M"
            atkadj="Str"
            dmgadj="Str"
            Damage="1d2/1"
            Range="Melee"
            Type="-"
            Speed="8"
            Weight="2"
            dosh=dosh-10
            wplist.pop([0])
        elif wplist[0]=="Matchlock Cavlier" and dosh>300: #Misfire on roll of a 1. Chance for misfire increases every 3 shots until cleaned. Explosion on 8's"
            RoF="1/2"
            atkadj="Dex"
            dmgadj="0"
            Damage="1d8/1d8"
            Range="40/80/2400"
            Type="B"
            Speed="9"
            Weight="11"
            dosh=dosh-300
            wplist.pop([0])
        elif wplist[0]=="Matchlock Musket" and dosh>2000: #Misfire on roll of a 1. Chance for misfire increases every 3 shots until cleaned. Explosion on 8's 10's and 12's"
            RoF="1/2"
            atkadj="Dex"
            dmgadj="0"
            Damage="1d12/1d12"
            Range="60/120/360"
            Type="B"
            Speed="12"
            Weight="20"
            dosh=dosh-2000
            wplist.pop([0])
        elif wplist[0]=="Snaplock Pistol" and dosh>4500: #Misfire on roll of a 3 or lower. Chance for misfire increases every 3 shots until cleaned. Explosion on 8's"
            RoF="1"
            atkadj="Dex"
            dmgadj="0"
            Damage="1d8/1d8"
            Range="15/30/45"
            Type="B"
            Speed="6"
            Weight="3"
            dosh=dosh-4500
            wplist.pop([0])
        elif wplist[0]=="Snaplock Musket" and dosh>8500: #Misfire on roll of a 3 or lower. Chance for misfire increases every 3 shots until cleaned. Explosion on 8's, 10' and 12's"
            RoF="1"
            atkadj="Dex"
            dmgadj="0"
            Damage="1d12/1d12"
            Range="65/130/390"
            Type="B"
            Speed="8"
            Weight="14"
            dosh=dosh-8500
            wplist.pop([0])
        elif wplist[0]=="Improvised" and dosh>200:
            RoF="M"
            atkadj="Str"
            dmgadj="Str"
            Damage="1d4+1/1d4"
            Range="Melee"
            Type="B"
            Speed="4"
            Weight="6"
            dosh=dosh-200
            wplist.pop([0])
